version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_nest
    restart: always
    environment:
      POSTGRES_USER: petshop
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pet_shop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
